# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
r:
  - bioc-devel

cache: packages

install:
- R -e 'devtools::install_deps(dep = c("Depends", "Imports")'

after_success:
  - Rscript -e 'covr::codecov()'

notifications:
  email:
    on_success: change
    on_failure: change
