# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
r:
  - bioc-devel
  - bioc-release
sudo: false
cache: packages

bioc_packages:
  - SummarizedExperiment

after_success:
  - Rscript -e 'covr::codecov()'

notifications:
  email:
    on_success: change
    on_failure: change
